# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('first_name', 'last_name', 'phone_number')]),
        ),
    ]
