# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


def move_phone_to_separate_table(apps, schema_editor):
    Phone = apps.get_model('users', 'Phone')
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        phone, _ = Phone.objects.get_or_create(number=user.phone_number)
        user.phone_numbers.add(phone)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171030_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='users', to='users.Phone'),
        ),
        migrations.RunPython(move_phone_to_separate_table),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
